export const APP_PORT = 'APP_PORT';
export const ENV_MODE = 'ENV_MODE';
export const API_BASE_URL = 'API_BASE_URL';
export const MONGO_CONNECTION_STRING = 'MONGO_CONNECTION_STRING';
export const CLIENT_BASE_URL = 'CLIENT_BASE_URL';

// Firebase
export const FIREBASE_API_KEY = 'FIREBASE_API_KEY'
export const FIREBASE_AUTH_DOMAIN = 'FIREBASE_AUTH_DOMAIN'
export const FIREBASE_PROJECT_ID = 'FIREBASE_PROJECT_ID'
export const FIREBASE_STORAGE_BUCKET = 'FIREBASE_STORAGE_BUCKET'
export const FIREBASE_MESSAGING_SENDER_ID = 'FIREBASE_MESSAGING_SENDER_ID'
export const FIREBASE_APP_ID = 'FIREBASE_APP_ID' 